[audio]
enable_overdrive = true
enable_sounds = true
notification_sound = ""

[bar.default]
capsule = true
center = [ "group:g2" ]
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "volume", "battery", "control-center" ]
font_family = "SF Pro Text"
font_weight = 600
scale = 1.1000000089406967
shadow = false
start = [ "group:g1", "media" ]

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "workspaces", "active_window" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "clock", "date" ]
    opacity = 1.0
    padding = 6.0

[brightness]
enable_ddcutil = true
minimum_brightness = 0.14999999664723873

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
enabled = true
pinned = [ "ghostty", "brave-browser", "thunar" ]
reserve_space = false
shadow = false
show_dots = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    resume_command = "noctalia:nightlight-enable"
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 660.0

[location]
address = "Recife, Brazil"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[nightlight]
enabled = true
force = true
temperature_day = 3700

[shell]
font_family = "SF Pro Text"
launch_apps_as_systemd_services = true
niri_overview_type_to_launch_enabled = true
polkit_agent = true
ui_scale = 1.4000000134110451

    [shell.launcher]
    session_search = true

    [shell.panel]
    shadow = false

    [shell.screenshot]
    confirm_region = true
    directory = "/home/pedro/Pictures/Screenshots"

[theme]
builtin = "Kanagawa"
community_palette = "Kanagawa Dragon"
source = "community"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "hyprland", "qt", "starship" ]

[wallpaper]
transition = [ "fade" ]

    [wallpaper.default]
    path = "/home/pedro/Pictures/Wallpapers/catholicon-holy-sepulchre.jpg"

    [wallpaper.last]
    path = "/home/pedro/Pictures/Wallpapers/catholicon-holy-sepulchre.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/pedro/Pictures/Wallpapers/catholicon-holy-sepulchre.jpg"

    [[wallpaper.favorite]]
    path = "/home/pedro/Pictures/Wallpapers/altar-basilica-sao-pedro.jpg"
    theme_mode = "auto"

[widget.active_window]
display = "icon_only"
icon_size = 18
min_length = 0

[widget.battery]
hide_when_plugged = true

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false