config_version = 2

[accessibility]
ui_scale = 1.300000011920929

[audio]
enable_overdrive = true
enable_sounds = true

[bar.default]
center = [ "cpu", "temp", "ram", "power_profile" ]
end = [ "tray", "notifications", "volume", "battery", "clock", "date", "control-center" ]
font_family = "SF Pro Text"
font_weight = 600
margin_edge = 5
radius = 25
shadow = false
start = [ "workspaces", "media", "active_window" ]
thickness = 32
widget_spacing = 15

[brightness]
enable_ddcutil = true
minimum_brightness = 0.14999999664723873

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
enabled = true
pinned = [ "ghostty", "brave-browser", "thunar" ]
reserve_space = false
shadow = false
show_dots = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = false
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    resume_command = "noctalia:nightlight-enable"
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 660.0

[location]
address = "Recife, Brazil"

[lockscreen]
wallpaper = "/home/pedro/Pictures/Wallpapers/mountain-above-clouds.jpg"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 640.0
    cy = 601.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[nightlight]
enabled = true
force = true
temperature_day = 3700

[osd]
scale = 1.2500000111758709

[shell]
avatar_path = "/home/pedro/dotfiles/backgrounds/ecclesiae-images/christ-pantocrator-holysepulchre.png"
font_family = "SF Pro Text"
launch_apps_as_systemd_services = true
niri_overview_type_to_launch_enabled = true
polkit_agent = true
ui_scale = 1.4000000134110451

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    session_search = true

    [shell.panel]
    shadow = false

    [shell.screenshot]
    confirm_region = true
    directory = "/home/pedro/Pictures/Screenshots"

[theme]
builtin = "Kanagawa"
community_palette = "Kanagawa Dragon"
custom_palette = "Kurodo"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "hyprland", "qt", "starship" ]
    community_ids = [ "pywalfox-beta4" ]

[wallpaper]
transition = [ "fade" ]

    [wallpaper.default]
    path = "/home/pedro/Pictures/Wallpapers/mountain-above-clouds.jpg"

    [wallpaper.last]
    path = "/home/pedro/Pictures/Wallpapers/mountain-above-clouds.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/pedro/Pictures/Wallpapers/mountain-above-clouds.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/pedro/Pictures/Wallpapers/mountain-above-clouds.jpg"

    [[wallpaper.favorite]]
    builtin_palette = "Kanagawa"
    palette_source = "builtin"
    path = "/home/pedro/Pictures/Wallpapers/mountain-above-clouds.jpg"
    theme_mode = "dark"

[widget.active_window]
icon_size = 18
min_length = 0

[widget.battery]
hide_when_plugged = true

[widget.bluetooth]
hide_when_no_connected_device = true

[widget.clipboard]
capsule = true

[widget.cpu]
display = "text"

[widget.date]
format = "{:%a %d, %b}"

[widget.media]
album_art_only = true
hide_when_no_media = true

[widget.network]
show_label = false

[widget.ram]
display = "text"

[widget.temp]
display = "text"
highlight_color = "primary"

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.workspaces]
capsule_radius = "auto"