# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nix_shell\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$time\
$line_break\
$character\
$container\
"""
add_newline = true

[line_break]
disabled = false

[os]
disabled = false
style = "bold blue"
format = "[$symbol]($style) "

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = true
ssh_symbol = " "
format = "[$ssh_symbol](bold gray) at [$hostname](bold green) "
disabled = false

[container]
symbol = " "
style = "bold red dimmed"
format = '[$symbol \[$name\]]($style) '

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[aws]
symbol = "  "

[c]
symbol = " "

[directory]
read_only = " 󰌾"
format = " in [$path](bold yellow) "

[docker_context]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "  "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[nix_shell]
symbol = " "

[os.symbols]
Alpine = " "
Arch = " "
CentOS = " "
Debian = " "
Fedora = " "
NixOS = " "
Kali = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[custom.update]
when = "/usr/bin/rpm-ostree status --json | /usr/bin/jq -e \".deployments[0].booted == false\" > /dev/null;"
command = 'echo "New deployment staged"'
symbol = ""
format = " $symbol [($output)]($style) "
style = "italic green"

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually
